---
title: Thomas Thornton
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/img
  values:
    image: true
- scope:
    path: ''
    type: pages
  values:
    meta title: 
    meta description: 
    language: 
    page ref: 
    exclude from sitemap: false
email: ThomasKThornton@aol.com
phone:
  english: '0049-157-3812-3118'
  deutsch: 'Mobil: 0049 157 38 12 31 18'
description: Ihr verlässlicher Partner für Übersetzungen aus dem Englischen oder ins
  Englische sowie Lektorate – mit über 20 Jahren Erfahrung in allen Bereichen von
  Kunst und Kultur sowie nahezu sämtlichen Zweigen von Wirtschaft und Industrie.
url: https://www.thomas-thornton.com
logo: "/assets/img/tt-logo.png"
language directories:
  english: "/"
  deutsch: "/de/"
top navigation:
  english:
  - title: Home
  - title: About Me
  - title: Language Services
  - title: Contact
  deutsch:
  - title: Startseite
  - title: Über mich
  - title: Sprachdienste
  - title: Kontakt
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
