---
title: Thomas Thornton
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: assets/img
  values:
    image: true
- scope:
    path: ''
    type: pages
  values:
    meta title:
    meta description:
    language:
    page ref:
    exclude from sitemap: false
email: ThomasKThornton@aol.com
phone:
  english: '0049-157-3812-3118'
  deutsch: 'Mobil: 0049 157 38 12 31 18'
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
url: https://www.thomaskthornton.com
logo: "/assets/img/tt-logo.png"
language directories:
  english: "/"
  deutsch: "/de/"
top navigation:
  english:
  - title: Home
  - title: About Me
  - title: Language Services
  - title: Contact
  deutsch:
  - title: Startseite
  - title: Ãœber mich
  - title: Sprachdienste
  - title: Kontakt
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
